// funcsdoc regenerates FUNCTIONS.md from the source.
//
// FUNCTIONS.md said of itself "Generated from the source so it cannot drift",
// and it had drifted badly: it listed a file that no longer exists, missed
// five that do, and described signatures that had changed underneath it. The
// claim was true of how it was first written and of nothing after that.
//
// So this is the thing that makes the sentence true. It reads the tree, writes
// the tables, and -- the part that matters for keeping it worth reading -- it
// PRESERVES the hand-written blurb under each heading. Those carry the
// judgement about what a file is for, which no generator can produce; the
// tables are the part that goes stale, and the part a machine should own.
//
//	go run ./src/cmd/funcsdoc      # rewrite FUNCTIONS.md
//	go run ./src/cmd/funcsdoc -check # fail if it is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const docPath = "FUNCTIONS.md"

const header = `# Function reference

Every function in the tree, with what it takes and what it gives back.
**Regenerated by ` + "`go run ./src/cmd/funcsdoc`" + `**, so the tables cannot drift; the
reasoning for each lives in the code, and the defects found while reading them
are in ` + "`REVIEW.md`" + `.

The blurb under each heading is written by hand and is kept across
regenerations -- edit it here. Everything below it is generated, so edits to
the tables are lost.

A receiver in the first column means it is a method. ` + "`—`" + ` means none.
`

type fn struct{ recv, name, in, out string }

func main() {
	check := flag.Bool("check", false, "exit non-zero if FUNCTIONS.md is out of date")
	flag.Parse()

	// src, not ".": every .go file lives under it since the move, and naming
	// it keeps this walk out of the 101MB snappymail checkout beside the
	// source. FUNCTIONS.md itself stays at the repo root, with the rest of
	// the documentation, so this is still run from there.
	files, err := goFiles("src")
	if err != nil {
		fail(err)
	}
	blurbs, err := existingBlurbs(docPath)
	if err != nil {
		fail(err)
	}

	var b bytes.Buffer
	b.WriteString(header)
	for _, path := range files {
		fns, err := funcsIn(path)
		if err != nil {
			fail(err)
		}
		if len(fns) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## `%s`\n\n", path)
		if s := blurbs[path]; s != "" {
			fmt.Fprintf(&b, "%s\n\n", s)
		} else {
			// Named rather than left blank, so a new file is visibly missing
			// its sentence rather than quietly having none.
			fmt.Fprintf(&b, "_No description yet._\n\n")
		}
		b.WriteString("| receiver | function | inputs | outputs |\n|---|---|---|---|\n")
		for _, f := range fns {
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n",
				code(f.recv), f.name, code(f.in), code(f.out))
		}
	}

	if *check {
		old, err := os.ReadFile(docPath)
		// A tree with no FUNCTIONS.md at all is not a tree with a stale one.
		// The public copy of this project ships the source without the internal
		// documentation, so the file is legitimately absent there and build.sh
		// would otherwise stop dead on a fresh clone. Drift is still caught
		// wherever the file does exist, which is the case this check is for.
		if os.IsNotExist(err) {
			fmt.Printf("no %s -- nothing to check\n", docPath)
			return
		}
		if err != nil {
			fail(err)
		}
		if !bytes.Equal(old, b.Bytes()) {
			fmt.Fprintln(os.Stderr,
				"FUNCTIONS.md is out of date -- run: go run ./src/cmd/funcsdoc")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(docPath, b.Bytes(), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s\n", docPath)
}

// goFiles lists the tree's Go source, tests excluded: a test's helpers are not
// part of what the app does, and listing them would double the file.
func goFiles(root string) ([]string, error) {
	var out []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			switch info.Name() {
			case ".git", "dev_config", "static", "templates", "node_modules":
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			out = append(out, filepath.ToSlash(path))
		}
		return nil
	})
	// Package main at the root first, then everything nested, each
	// alphabetically -- the order somebody reads the tree in.
	sort.Slice(out, func(i, j int) bool {
		di, dj := strings.Contains(out[i], "/"), strings.Contains(out[j], "/")
		if di != dj {
			return !di
		}
		return out[i] < out[j]
	})
	return out, err
}

func funcsIn(path string) ([]fn, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	var out []fn
	for _, d := range f.Decls {
		fd, ok := d.(*ast.FuncDecl)
		if !ok {
			continue
		}
		out = append(out, fn{
			recv: fieldList(fd.Recv, false),
			name: fd.Name.Name,
			in:   fieldList(fd.Type.Params, false),
			out:  fieldList(fd.Type.Results, true),
		})
	}
	return out, nil
}

// fieldList renders a signature the way it is written in the source, so the
// table and the code read the same.
//
// parens is set for results only: Go writes multiple results in brackets and a
// parameter list without them, and the table reads as Go rather than as a
// convention of its own.
func fieldList(fl *ast.FieldList, parens bool) string {
	if fl == nil || len(fl.List) == 0 {
		return ""
	}
	var parts []string
	for _, f := range fl.List {
		t := types(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, t)
			continue
		}
		var names []string
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		parts = append(parts, strings.Join(names, ", ")+" "+t)
	}
	s := strings.Join(parts, ", ")
	if parens && (len(fl.List) > 1 || len(fl.List[0].Names) > 1) {
		return "(" + s + ")"
	}
	return s
}

func types(e ast.Expr) string {
	var b bytes.Buffer
	writeType(&b, e)
	return b.String()
}

func writeType(b *bytes.Buffer, e ast.Expr) {
	switch t := e.(type) {
	case *ast.Ident:
		b.WriteString(t.Name)
	case *ast.StarExpr:
		b.WriteByte('*')
		writeType(b, t.X)
	case *ast.SelectorExpr:
		writeType(b, t.X)
		b.WriteByte('.')
		b.WriteString(t.Sel.Name)
	case *ast.ArrayType:
		b.WriteString("[]")
		writeType(b, t.Elt)
	case *ast.MapType:
		b.WriteString("map[")
		writeType(b, t.Key)
		b.WriteByte(']')
		writeType(b, t.Value)
	case *ast.Ellipsis:
		b.WriteString("...")
		writeType(b, t.Elt)
	case *ast.FuncType:
		b.WriteString("func(")
		b.WriteString(fieldList(t.Params, false))
		b.WriteByte(')')
		if r := fieldList(t.Results, true); r != "" {
			b.WriteByte(' ')
			b.WriteString(r)
		}
	case *ast.InterfaceType:
		if t.Methods == nil || len(t.Methods.List) == 0 {
			b.WriteString("any")
			return
		}
		b.WriteString("interface{...}")
	case *ast.ChanType:
		b.WriteString("chan ")
		writeType(b, t.Value)
	case *ast.StructType:
		b.WriteString("struct{...}")
	default:
		b.WriteString("?")
	}
}

// existingBlurbs harvests the hand-written sentence under each heading, so a
// regeneration keeps what a person wrote and replaces only the table.
func existingBlurbs(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]string{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	var file string
	var buf []string
	flush := func() {
		if file != "" {
			if s := strings.TrimSpace(strings.Join(buf, "\n")); s != "" {
				out[file] = s
			}
		}
		file, buf = "", nil
	}
	for _, line := range strings.Split(string(raw), "\n") {
		switch {
		case strings.HasPrefix(line, "## `"):
			flush()
			file = strings.Trim(strings.TrimPrefix(line, "## "), "`")
		case strings.HasPrefix(line, "| receiver |"), strings.HasPrefix(line, "|---"):
			// The table starts here; everything after it is generated.
			if file != "" && len(buf) > 0 {
				flush2 := file
				if s := strings.TrimSpace(strings.Join(buf, "\n")); s != "" {
					out[flush2] = s
				}
				buf = nil
			}
		case strings.HasPrefix(line, "|"):
			// generated row, skip
		case file != "":
			buf = append(buf, line)
		}
	}
	flush()
	return out, nil
}

func code(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return "`" + s + "`"
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "funcsdoc:", err)
	os.Exit(1)
}
