package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// The Ollama Scan store: one SQLite file per mailbox, beside the config.
//
// **One file per mailbox rather than one table with an owner column.** Asked
// for so the size of each can be watched, and that is a real property: this
// data grows with how much mail somebody has sent and how much of it is
// questions, which is not something the app can bound. A file per mailbox
// means `ls -l` answers "who is using the disk", a mailbox that is removed
// takes its data with it in one unlink, and a scan of one mailbox cannot lock
// the writes of another -- SQLite takes one writer at a time per file.
//
// It is deliberately NOT in mail_client.db. That database is the app's own
// state: accounts, settings, contacts. This is derived data that can be
// regenerated by scanning again, and mixing the two would mean a backup of the
// accounts carried gigabytes of extracted text with it.

// scanDBName turns a provider and a mailbox address into a file name.
//
//	ollama, testuser@example.net -> ollama_sent_email_data_testuser_example_net.db
//	claude, testuser@example.net -> claude_sent_email_data_testuser_example_net.db
//
// **A file per provider as well as per mailbox.** The two scans are separate
// screens holding separate findings, so keeping them apart is what lets one be
// re-run without disturbing the other, lets a mailbox see what each model made
// of the same folder, and keeps "how big is this getting" answerable per
// provider -- which is the question the one-file-per-mailbox rule was for in
// the first place.
//
// Every character of the address that is not a letter or a digit becomes an
// underscore. That is stricter than escaping would be and loses the difference
// between a.b@x.com and a_b@x.com -- which is a collision, and is why the
// mapping is checked against the address stored inside the file when it is
// opened.
func scanDBName(provider, address string) string {
	var b strings.Builder
	b.WriteString(scanProviderPrefix(provider))
	b.WriteString("_sent_email_data_")
	for _, r := range strings.ToLower(strings.TrimSpace(address)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	b.WriteString(".db")
	return b.String()
}

// scanProviderPrefix is the leading word of the file name.
//
// An allowlist rather than the provider string itself: this becomes a path,
// and a name is not a thing to trust just because every caller currently
// passes a constant.
func scanProviderPrefix(provider string) string {
	switch strings.ToLower(strings.TrimSpace(provider)) {
	case "claude":
		return "claude"
	default:
		return "ollama"
	}
}

// scanSchema is applied on open. Additive only from here: unlike the app's own
// database this one holds work somebody waited for, and dropping it means
// running every message past the model again.
const scanSchema = `
PRAGMA journal_mode = WAL;

-- Which mailbox this file belongs to, written once.
--
-- It exists because scanDBName is lossy: two addresses can produce one file
-- name, and without this the second mailbox would silently inherit the
-- first's findings. Opening checks it and refuses a mismatch.
CREATE TABLE IF NOT EXISTS owner (
    address    TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- One row per message the scanner has looked at.
--
-- **Keyed by Message-ID**, not by UID. A UID is per-folder and does not
-- survive the folder being recreated, so a mailbox that was rebuilt would
-- rescan everything; Message-ID is assigned by whatever sent the message and
-- stays with it. folder and uid are kept anyway, as the way back to the
-- message on the server, but they are a pointer rather than the identity.
--
-- A message with no Message-ID at all is real -- some senders omit it -- and
-- is recorded under a synthetic one derived from the folder and UID. That is
-- weaker: rebuild the folder and it will be scanned again. Named rather than
-- hidden, in synthetic_id.
CREATE TABLE IF NOT EXISTS scanned (
    message_id   TEXT PRIMARY KEY,
    synthetic_id INTEGER NOT NULL DEFAULT 0,
    folder       TEXT NOT NULL,
    uid          INTEGER NOT NULL,
    sent_at      TEXT NOT NULL DEFAULT '',
    recipients   TEXT NOT NULL DEFAULT '',
    subject      TEXT NOT NULL DEFAULT '',

    scanned_at   TEXT NOT NULL,
    -- 'ok' or 'failed'. A failure is recorded rather than left unscanned, so
    -- the next scan does not spend the model's time on it again -- and the
    -- reason is kept so somebody can see why.
    status       TEXT NOT NULL DEFAULT 'ok',
    error        TEXT NOT NULL DEFAULT '',
    -- The model that produced the findings, so a re-scan under a different
    -- model is a visible difference rather than a silent one.
    model        TEXT NOT NULL DEFAULT '',
    found        INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_scanned_at ON scanned (scanned_at);

-- What the model found, quoted from the message.
CREATE TABLE IF NOT EXISTS qa (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id TEXT NOT NULL REFERENCES scanned (message_id) ON DELETE CASCADE,
    -- 'question' or 'answer'. They are not paired: the brief is to find both
    -- in the text, not to match one to the other.
    kind       TEXT NOT NULL,
    text       TEXT NOT NULL,

    -- WHERE it came from: the byte offset of the quote in the stripped text,
    -- and -1 when the quote could not be found there.
    --
    -- That second case is the point of storing it. The model is asked to quote
    -- verbatim; searching the source for what it returned is the only way to
    -- know whether it did. A -1 is a paraphrase or an invention, and it is
    -- recorded rather than dropped so the rate is visible.
    offset     INTEGER NOT NULL DEFAULT -1,
    verbatim   INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_qa_message ON qa (message_id);
CREATE INDEX IF NOT EXISTS idx_qa_kind ON qa (kind);
`

// ScanStore is one mailbox's findings from one provider.
type ScanStore struct {
	db       *sql.DB
	address  string
	provider string
	path     string
}

// scanStores keeps one open handle per file.
//
// Opening per request would be cheap in itself, but two handles to one SQLite
// file are two writers, and the second gets SQLITE_BUSY rather than a queue.
// One handle per mailbox for the life of the process, created on first use.
type scanStores struct {
	mu   sync.Mutex
	dir  string
	open map[string]*ScanStore
}

func newScanStores(dir string) *scanStores {
	return &scanStores{dir: dir, open: map[string]*ScanStore{}}
}

// For returns the store for one provider and one mailbox, creating the file on
// first use.
func (s *scanStores) For(ctx context.Context, provider, address string) (*ScanStore, error) {
	address = normaliseAddress(address)
	if address == "" {
		return nil, fmt.Errorf("no mailbox to scan for")
	}
	provider = scanProviderPrefix(provider)
	// Keyed by both, because one mailbox now has two files and a map keyed by
	// address alone would hand the second scan the first one's handle -- and
	// with it the first one's findings.
	key := provider + " " + address
	s.mu.Lock()
	defer s.mu.Unlock()
	if st, ok := s.open[key]; ok {
		return st, nil
	}
	st, err := openScanStore(ctx, s.dir, provider, address)
	if err != nil {
		return nil, err
	}
	s.open[key] = st
	return st, nil
}

// Close releases every open handle, for shutdown.
func (s *scanStores) Close() {
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, st := range s.open {
		st.db.Close()
	}
	s.open = map[string]*ScanStore{}
}

func openScanStore(ctx context.Context, dir, provider, address string) (*ScanStore, error) {
	path := filepath.Join(dir, scanDBName(provider, address))
	// The same connection settings as the app's own database, for the same
	// reasons -- see OpenDB.
	db, err := sql.Open("sqlite",
		path+"?_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)&_txlock=immediate")
	if err != nil {
		return nil, fmt.Errorf("cannot open %s: %w", path, err)
	}
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)

	if _, err := db.ExecContext(ctx, scanSchema); err != nil {
		db.Close()
		return nil, fmt.Errorf("cannot prepare %s: %w", path, err)
	}

	// Claim the file, or check the claim. scanDBName is lossy, so two
	// addresses can name one file; without this the second would read the
	// first's findings as its own.
	var owner string
	err = db.QueryRowContext(ctx, `SELECT address FROM owner LIMIT 1`).Scan(&owner)
	switch {
	case err == sql.ErrNoRows:
		if _, err := db.ExecContext(ctx,
			`INSERT INTO owner (address, created_at) VALUES (?, ?)`,
			address, Now()); err != nil {
			db.Close()
			return nil, err
		}
	case err != nil:
		db.Close()
		return nil, err
	case owner != address:
		db.Close()
		return nil, fmt.Errorf(
			"%s already belongs to %s, so %s cannot use it -- two addresses "+
				"produced the same file name", path, owner, address)
	}
	return &ScanStore{db: db, address: address,
		provider: scanProviderPrefix(provider), path: path}, nil
}

// Path is where the file is, for the screen that reports its size.
func (s *ScanStore) Path() string { return s.path }

// ScanState is what is known about one message that has been through.
//
// Kept small on purpose: it is what the Sent list needs for its Scanned
// column, not the findings themselves.
type ScanState struct {
	Status string // "ok" or "failed"
	Error  string
	Found  int
	// MessageID is how the row links through to what was found in it. The
	// list has UIDs; the store is keyed by Message-ID, and the reader should
	// not have to be told the difference.
	MessageID string
}

// Scanned reports which of these Message-IDs have been looked at already.
func (s *ScanStore) Scanned(ctx context.Context, ids []string) (map[string]bool, error) {
	states, err := s.States(ctx, ids)
	if err != nil {
		return nil, err
	}
	out := make(map[string]bool, len(states))
	for id := range states {
		out[id] = true
	}
	return out, nil
}

// States is the same question with the answer attached, for the screen.
func (s *ScanStore) States(ctx context.Context, ids []string) (map[string]ScanState, error) {
	out := map[string]ScanState{}
	if len(ids) == 0 {
		return out, nil
	}
	// One query with an IN list rather than one per message: a page of fifty
	// is fifty round trips otherwise, to answer one question.
	q := `SELECT message_id, status, error, found FROM scanned WHERE message_id IN (?` +
		strings.Repeat(",?", len(ids)-1) + `)`
	args := make([]any, len(ids))
	for i, id := range ids {
		args[i] = id
	}
	rows, err := s.db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var id string
		var st ScanState
		if err := rows.Scan(&id, &st.Status, &st.Error, &st.Found); err != nil {
			return nil, err
		}
		st.MessageID = id
		out[id] = st
	}
	return out, rows.Err()
}

// ScanTotals is the whole store at a glance, for the section header.
type ScanTotals struct {
	Messages  int
	Questions int
	Answers   int
	Failed    int
	// File and Size are the point of one database per mailbox: somebody asked
	// to be able to watch how big each one gets, so the screen says.
	File string
	Size int64
}

// Counts is what the screen reports: how many messages and findings are held.
func (s *ScanStore) Counts(ctx context.Context) (messages, questions, answers, failed int, err error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT (SELECT COUNT(*) FROM scanned),
		       (SELECT COUNT(*) FROM qa WHERE kind = 'question'),
		       (SELECT COUNT(*) FROM qa WHERE kind = 'answer'),
		       (SELECT COUNT(*) FROM scanned WHERE status <> 'ok')`)
	err = row.Scan(&messages, &questions, &answers, &failed)
	return
}

// FindingRow is one stored quote with the message it came from.
//
// The message's details are copied onto the row rather than left as an ID for
// the caller to resolve: this store is read on a screen that has no IMAP
// connection open, and going back to the server to put a date beside a quote
// would make reading the findings as slow as making them.
type FindingRow struct {
	Kind       string
	Text       string
	Offset     int
	Verbatim   bool
	MessageID  string
	Synthetic  bool
	Subject    string
	Recipients string
	SentAt     time.Time
	Folder     string
	UID        uint32
}

// FindingQuery narrows the list on screen.
type FindingQuery struct {
	Kind      string // "", "question" or "answer"
	MessageID string // one message, when the reader came from its row
	Verbatim  string // "", "yes" or "no"
	Page      int
	PerPage   int
}

// Findings reads back what was found, newest message first.
//
// Ordered by the message's own date rather than by when it was scanned: the
// reader is looking for what they said in some piece of correspondence, and
// the order the scanner happened to work through the folder means nothing to
// them.
func (s *ScanStore) Findings(ctx context.Context, q FindingQuery) ([]FindingRow, int, error) {
	where := []string{"1 = 1"}
	var args []any
	if q.Kind == "question" || q.Kind == "answer" {
		where = append(where, "qa.kind = ?")
		args = append(args, q.Kind)
	}
	if q.MessageID != "" {
		where = append(where, "qa.message_id = ?")
		args = append(args, q.MessageID)
	}
	switch q.Verbatim {
	case "yes":
		where = append(where, "qa.verbatim = 1")
	case "no":
		where = append(where, "qa.verbatim = 0")
	}
	cond := strings.Join(where, " AND ")

	var total int
	if err := s.db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM qa WHERE `+cond, args...).Scan(&total); err != nil {
		return nil, 0, err
	}

	if q.PerPage <= 0 {
		q.PerPage = 50
	}
	if q.Page < 1 {
		q.Page = 1
	}
	rows, err := s.db.QueryContext(ctx, `
		SELECT qa.kind, qa.text, qa.offset, qa.verbatim, qa.message_id,
		       scanned.synthetic_id, scanned.subject, scanned.recipients,
		       scanned.sent_at, scanned.folder, scanned.uid
		  FROM qa
		  JOIN scanned ON scanned.message_id = qa.message_id
		 WHERE `+cond+`
		 ORDER BY scanned.sent_at DESC, qa.message_id, qa.id
		 LIMIT ? OFFSET ?`,
		append(args, q.PerPage, (q.Page-1)*q.PerPage)...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	out := make([]FindingRow, 0, q.PerPage)
	for rows.Next() {
		var f FindingRow
		var verbatim, synthetic int
		var sentAt string
		if err := rows.Scan(&f.Kind, &f.Text, &f.Offset, &verbatim, &f.MessageID,
			&synthetic, &f.Subject, &f.Recipients, &sentAt, &f.Folder, &f.UID); err != nil {
			return nil, 0, err
		}
		f.Verbatim, f.Synthetic = verbatim == 1, synthetic == 1
		// A date that will not parse is left zero rather than refused: it is a
		// column on a screen, not something anything depends on.
		f.SentAt, _ = time.Parse(time.RFC3339, sentAt)
		out = append(out, f)
	}
	return out, total, rows.Err()
}

// Finding is one quote the model returned.
type Finding struct {
	Kind     string // "question" or "answer"
	Text     string
	Offset   int
	Verbatim bool
}

// Record stores one scanned message and everything found in it, in one
// transaction: a message counted as scanned whose findings were not written
// would never be looked at again.
func (s *ScanStore) Record(ctx context.Context, m ScanRecord, found []Finding) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	now := Now()
	if _, err := tx.ExecContext(ctx, `
		INSERT INTO scanned (message_id, synthetic_id, folder, uid, sent_at,
		                     recipients, subject, scanned_at, status, error,
		                     model, found)
		VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
		ON CONFLICT(message_id) DO UPDATE SET
		    folder = excluded.folder, uid = excluded.uid,
		    scanned_at = excluded.scanned_at, status = excluded.status,
		    error = excluded.error, model = excluded.model,
		    found = excluded.found`,
		m.MessageID, boolToInt(m.Synthetic), m.Folder, m.UID, m.SentAt,
		m.Recipients, m.Subject, now, m.Status, m.Error, m.Model, len(found),
	); err != nil {
		return err
	}

	// A re-scan replaces what was found before rather than adding to it.
	if _, err := tx.ExecContext(ctx,
		`DELETE FROM qa WHERE message_id = ?`, m.MessageID); err != nil {
		return err
	}
	for _, f := range found {
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO qa (message_id, kind, text, offset, verbatim, created_at)
			VALUES (?,?,?,?,?,?)`,
			m.MessageID, f.Kind, f.Text, f.Offset, boolToInt(f.Verbatim), now,
		); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// ScanRecord is what is known about a message once it has been through.
type ScanRecord struct {
	MessageID  string
	Synthetic  bool
	Folder     string
	UID        uint32
	SentAt     string
	Recipients string
	Subject    string
	Status     string // "ok" or "failed"
	Error      string
	Model      string
}

// syntheticMessageID names a message that arrived without a Message-ID.
//
// Folder and UID, which is the weaker key: recreate the folder and the same
// message scans again. Prefixed so it can never collide with a real one and so
// the rows are findable.
func syntheticMessageID(folder string, uid uint32) string {
	return fmt.Sprintf("synthetic:%s:%d", folder, uid)
}

// scanFileSize is what the screen shows, since watching it is why there is a
// file per mailbox.
//
// **The write-ahead log counts.** In WAL mode a freshly written database is
// mostly its -wal file until SQLite checkpoints: the first real scan on this
// machine left a 4 KB .db beside a 255 KB -wal, and a screen that reported
// "4 KB" would have been answering the question wrong in the exact case
// somebody is watching for -- just after a lot of writing. The -shm is counted
// too; it is small, but it is disk this mailbox is using.
func scanFileSize(path string) int64 {
	var total int64
	for _, p := range []string{path, path + "-wal", path + "-shm"} {
		if fi, err := os.Stat(p); err == nil {
			total += fi.Size()
		}
	}
	return total
}
